### ISSUE TITLE
FR: Custom hotlink redirect

### ISSUE THREAD

**Issue by mdmower** [download-monitor/download-monitor#258]
Feature request: Allow specifying the redirect page(s) when hotlinking is disabled.

Each download (but not necessarily each version of a download) can specify an individual redirect page. If a redirect page is not specified the default redirect is used. The default redirect can also be configured.

As a side note, regarding Issue #244, I do not experience this problem.

**Comment by mdmower** [comment]
I will be very, very slowly working on this feature at https://github.com/mdmower/download-monitor/commits/dev . Please take-over development if you find time to implement this yourself (I'm not offended in the slightest if my code is completely disregarded).

**Comment by barrykooij** [comment]
The redirect URL is filterable at the moment with the filter ```dlm_hotlink_redirect``` but this filter doesn't include the download ID. Instead of making this an option I will include the download ID in the ```dlm_hotlink_redirect``` filter so you can set the hotlink prevent redirect URL with a filter in your theme or a custom plugin. I've added this to the 1.7.0 milestone.

Thanks for letting me know about #244

**Comment by barrykooij** [comment]
Fixed this in 1.7.0
