### ISSUE TITLE
Logs > Blacklist IPs not working

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#297]
Functionality seems to be not working.

**Comment by mdmower** [comment]
I have this implemented for IPv4 addresses and user agents here: [mdmower/download-monitor/commits/dev11](https://github.com/mdmower/download-monitor/commits/dev11). Note that I've changed for address range specification from wildcard to CIDR. It would be nice to provide some migration for wildcard masks to CIDR masks, but I wasn't so enthusiastic about spending time on this since the feature never worked to begin with.

Checking whether an IPv6 address falls in a range will require another function be written. A skeleton for support exists in check_access(), but I have not yet taken on the task to writing the range-check function.

**Comment by mdmower** [comment]
Ok, IPv6 support has been added to the above mentioned branch. One caveat is that Windows users need at least PHP 5.3.0 for IPv6 checking to work. A function_exists check is made on inet_pton in case it does not, but no alternative methods are provided and instead IPv6 blacklisting will simply not work (no errors should be thrown).

All of this needs careful scrutiny... I'm sure this goes without saying.

**Comment by barrykooij** [comment]
@mdmower had a look at your branch, looks good! :+1: Are you completely restricting access to the download by the way?

**Comment by barrykooij** [comment]
Did some tweaks and merged this in master. Thanks @mdmower, awesome work as always :+1:
