### ISSUE TITLE
Ninja Forms needs to be activated for the Download Monitor Ninja Forms Extension!

### ISSUE THREAD

**Issue by axteleraray** [download-monitor/download-monitor#471]
Hi,
I am facing issue while working on my website, I have purchased and activated the "Ninja Forms" extension but I am still seeing the message on top "Ninja Forms needs to be activated for the Download Monitor Ninja Forms Extension!"
![screenshot_15](https://user-images.githubusercontent.com/10787849/35529571-54989aa6-0529-11e8-9282-ab36c6cdced7.jpg)

Can any one please help me to solve this issue,

Thank you

**Comment by hchouhan** [comment]
Hello,

Please note that the "Ninja Forms Lock" is an extension to lock a download created with "Download Monitor" using a form builder plugin called "Ninja Forms". The message you see is because you have not installed the "Ninja Forms" plugin. You can download this plugin at https://wordpress.org/plugins/ninja-forms/.

**Comment by barrykooij** [comment]
Ninja Forms plugin indeed also needs to be installed. Please contact us via https://www.download-monitor.com/contact/ for further help.
