### ISSUE TITLE
download slug not used in themes ajax search.

### ISSUE THREAD

**Issue by ieanea** [download-monitor/download-monitor#477]
The download slug does not seem to work in my themes ajax search.  The ajax search results will show: mydomain/?post_type=dlm_download&p=47741 which gets an error.  While the regular wordpress results would be mydomain/downloads/mydocument

**Comment by barrykooij** [comment]
hey @ieanea ,

What are you using for ajax search? This is not included in core right? Are you using a plugin for this?

Kind Regards,

Barry Kooij

**Comment by ieanea** [comment]
It is part of the newspaper theme. https://themeforest.net/item/newspaper/5489609
It gives search suggestions  when typing.   Is there something that can me done to make sure it uses the dm slug?

**Comment by barrykooij** [comment]
Looks like your theme has its own form of search implemented. Download Monitor uses a filter on the permalink to set our own download slug. Please contact your theme author and ask them to respect this. If they can't or don't want to, please ask them to look at https://github.com/download-monitor/download-monitor/blob/master/src/Search.php
That file should help them include support for Download Monitor in their theme.

I'm closing this issue here since this isn't a bug in our plugin and we like to keep this issue tracker just for issues (not support). If you need further help, please feel free to open a ticket here: https://wordpress.org/support/plugin/download-monitor

Kind Regards,

Barry Kooij
