### ISSUE TITLE
getting downloading page blank

### ISSUE THREAD

**Issue by akshayjondhale** [download-monitor/download-monitor#502]
getting downloading page black when click on download button

**Comment by barrykooij** [comment]
@akshayjondhale is this related to Download Monitor or to one of our extensions? Did you try to re-save your permalinks?

**Comment by taich001** [comment]
After installing Download Monitor I can not use download any more as a page link.
I have a wordpress page named "download" with permalink www.example.com/download. This page is not shown any more. If I try to display it I will be redirected to start page.

**Comment by IamNoobDude** [comment]
It's related to Download Monitor extension - Downloading Page[https://www.download-monitor.com/kb/downloading-page/](url)

When we click on a download, The page is just opened but just blank.

**Comment by taich001** [comment]
This seems to be not optimal. Since I use in main menu a link call "Download". So if I want to use download-monitor I can not use this link any more. Even worse since Google has already indexed my download link which does not work any more.

What finally leads to the solution not to use download-monitor.

**Comment by barrykooij** [comment]
I'm closing this issue because of the original creator didn't respond. If anyone in this thread is still running into issues, please create a separate issue.
