### ISSUE TITLE
Fatal error when changing dates in reports

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#508]
php server PHP 7.1.17.

When changing the date to see a report an error occurs, I have tried with different dates and the result is always the same. Attached error indicated.

```
Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (NaN-NaN-NaN) at position 0 (N): The timezone could not be found in the database in /wp-content/plugins/download-monitor/src/Admin/Reports/Page.php:61 Stack trace: #0 /wp-content/plugins/download-monitor/src/Admin/Reports/Page.php(61): DateTime->__construct(‘NaN-NaN-NaN’) #1 /wp-content/plugins/download-monitor/src/Admin/Reports/Page.php(171): DLM_Reports_Page->get_date_range() #2 /wp-includes/class-wp-hook.php(286): DLM_Reports_Page->view(”) #3 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(”, Array) #4 /wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /wp-admin/admin.php(224): do_action(‘dlm_download_pa…’) #6 /home/auxald in /wp-content/plugins/download-monitor/src/Admin/Reports/Page.php on line 61
```

I attach the code line

```
$ to_date = new DateTime ($ to);
```

The version of the plugins that I have installed is 4.0.7 and 4.9.5 in WordPress. Could you help me?

**Comment by barrykooij** [comment]
I've tested this in Chrome, Firefox and Opera. There is no Safari for Ubuntu available, I'll have to look into debugging this later. Pushing this back.

**Comment by plaurent75** [comment]
The Problem is still occuring with safari with DLM 4.1.0
Selecting a date in admin report is not working causing a fatal error with PHP, but the original bug come from the js file.

When selecting a date, the format is not correctly set from the js script :
/wp-admin/edit.php?post_type=dlm_download&page=download-monitor-reports&tab=totals&chart=line&period=day&date_from=NaN-NaN-NaN&date_to=NaN-NaN-NaN

The cause is a know trouble:

https://stackoverflow.com/questions/21883699/safari-javascript-date-nan-issue-yyyy-mm-dd-hhmmss

http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

> Alternatively, the date/time string may be in ISO 8601 format. For example, "2011-10-10" (just date) or "2011-10-10T14:48:00" (date and time) can be passed and parsed.

**Comment by barrykooij** [comment]
Should be fixed in upcoming release. I will need to test this on a Mac when there is a stable beta.
